### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jothan** [seclytics/python-client#1]
I needed to tweak this library slightly to be able to use seclytics.scripts.ip_filter with Python 3.6.

I've had to modify ip_filter in seclytics/bloom_category.py and PortableBloom.contains.

Python 2.7 is scheduled to be phased out in 4 months: https://python3statement.org/

**Comment by cowholio4** [comment]
Can you submit a PR with the tweaks you made?

**Comment by cowholio4** [comment]
@jothan we made changes to allow for Python 3 compatibility.
